// packages/embed-react/src/index.tsx
import {
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  forwardRef,
  type CSSProperties,
} from "react";
import {
  MontiEmbed,
  type EmbedError,
  type EmbedPosition,
  type EmbedResolveResult,
} from "@monti/embed-core";

export type { EmbedError, EmbedPosition, EmbedResolveResult };
export { MontiEmbed };

export interface MontiEmbedProps {
  embedKey: string;
  apiBase: string;
  parentOrigin?: string;
  position?: EmbedPosition;
  agentId?: string;
  theme?: string;
  locale?: string;
  /** Controlled open state (floating mode). */
  open?: boolean;
  /** Uncontrolled initial open. */
  defaultOpen?: boolean;
  /** Mount iframe inside the component host (inline). */
  inline?: boolean;
  skipResolve?: boolean;
  className?: string;
  style?: CSSProperties;
  onOpen?: () => void;
  onClose?: () => void;
  onReady?: (result?: EmbedResolveResult) => void;
  onError?: (error: EmbedError) => void;
  onDestroy?: () => void;
  onOpenChange?: (open: boolean) => void;
}

export interface MontiEmbedHandle {
  open: () => void;
  close: () => void;
  toggle: () => void;
  destroy: () => void;
  getInstance: () => MontiEmbed | null;
}

export const MontiEmbedReact = forwardRef<MontiEmbedHandle, MontiEmbedProps>(function MontiEmbedReact(
  props,
  ref,
) {
  const hostRef = useRef<HTMLDivElement | null>(null);
  const embedRef = useRef<MontiEmbed | null>(null);
  const [error, setError] = useState<EmbedError | null>(null);

  const {
    embedKey,
    apiBase,
    parentOrigin,
    position = "bottom-right",
    agentId,
    theme,
    locale,
    open,
    defaultOpen = false,
    inline = false,
    skipResolve = false,
    className,
    style,
    onOpen,
    onClose,
    onReady,
    onError,
    onDestroy,
    onOpenChange,
  } = props;

  // Keep latest callbacks without remounting
  const cb = useRef({ onOpen, onClose, onReady, onError, onDestroy, onOpenChange });
  cb.current = { onOpen, onClose, onReady, onError, onDestroy, onOpenChange };

  useEffect(() => {
    let cancelled = false;
    const embed = new MontiEmbed({
      embedKey,
      apiBase,
      parentOrigin,
      position,
      agentId,
      theme,
      locale,
      open: open ?? defaultOpen,
      skipResolve,
      container: inline ? hostRef.current : null,
      onOpen: () => {
        cb.current.onOpen?.();
        cb.current.onOpenChange?.(true);
      },
      onClose: () => {
        cb.current.onClose?.();
        cb.current.onOpenChange?.(false);
      },
      onReady: (r) => cb.current.onReady?.(r),
      onError: (e) => {
        if (!cancelled) setError(e);
        cb.current.onError?.(e);
      },
      onDestroy: () => cb.current.onDestroy?.(),
    });
    embedRef.current = embed;
    void embed.mount();

    return () => {
      cancelled = true;
      embed.destroy();
      if (embedRef.current === embed) embedRef.current = null;
    };
  }, [
    embedKey,
    apiBase,
    parentOrigin,
    position,
    agentId,
    theme,
    locale,
    inline,
    skipResolve,
    defaultOpen,
    // intentionally omit `open` — controlled via separate effect
  ]);

  useEffect(() => {
    if (open === undefined) return;
    const embed = embedRef.current;
    if (!embed) return;
    if (open) embed.open();
    else embed.close();
  }, [open]);

  useImperativeHandle(
    ref,
    () => ({
      open: () => embedRef.current?.open(),
      close: () => embedRef.current?.close(),
      toggle: () => embedRef.current?.toggle(),
      destroy: () => {
        embedRef.current?.destroy();
        embedRef.current = null;
      },
      getInstance: () => embedRef.current,
    }),
    [],
  );

  const hostStyle: CSSProperties = inline
    ? { width: "100%", minHeight: 480, height: "100%", ...style }
    : { display: "contents", ...style };

  return (
    <div
      ref={hostRef}
      data-monti-embed-react="1"
      data-error={error?.code}
      className={className}
      style={hostStyle}
    />
  );
});

/** Hook that owns a MontiEmbed instance for custom UI shells. */
export function useMontiEmbed(
  options: Omit<MontiEmbedProps, "className" | "style" | "inline"> & {
    container?: HTMLElement | null;
    enabled?: boolean;
  },
): {
  embed: MontiEmbed | null;
  error: EmbedError | null;
  open: () => void;
  close: () => void;
  toggle: () => void;
} {
  const embedRef = useRef<MontiEmbed | null>(null);
  const [error, setError] = useState<EmbedError | null>(null);
  const [tick, setTick] = useState(0);
  const enabled = options.enabled !== false;

  useEffect(() => {
    if (!enabled) {
      embedRef.current?.destroy();
      embedRef.current = null;
      return;
    }
    const embed = new MontiEmbed({
      embedKey: options.embedKey,
      apiBase: options.apiBase,
      parentOrigin: options.parentOrigin,
      position: options.position,
      agentId: options.agentId,
      theme: options.theme,
      locale: options.locale,
      open: options.open ?? options.defaultOpen,
      skipResolve: options.skipResolve,
      container: options.container ?? null,
      onOpen: options.onOpen,
      onClose: options.onClose,
      onReady: options.onReady,
      onError: (e) => {
        setError(e);
        options.onError?.(e);
      },
      onDestroy: options.onDestroy,
    });
    embedRef.current = embed;
    void embed.mount().then(() => setTick((t) => t + 1));
    return () => {
      embed.destroy();
      if (embedRef.current === embed) embedRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- remount on identity fields
  }, [
    enabled,
    options.embedKey,
    options.apiBase,
    options.parentOrigin,
    options.position,
    options.agentId,
    options.theme,
    options.locale,
    options.skipResolve,
    options.container,
  ]);

  const open = useCallback(() => embedRef.current?.open(), []);
  const close = useCallback(() => embedRef.current?.close(), []);
  const toggle = useCallback(() => embedRef.current?.toggle(), []);

  return {
    embed: tick >= 0 ? embedRef.current : null,
    error,
    open,
    close,
    toggle,
  };
}

export default MontiEmbedReact;

// packages/embed-web-component/src/index.ts
import {
  MontiEmbed,
  type EmbedError,
  type EmbedPosition,
  type EmbedResolveResult,
} from "@monti/embed-core";

export type { EmbedError, EmbedPosition, EmbedResolveResult };
export { MontiEmbed };

const OBSERVED = [
  "embed-key",
  "api-base",
  "parent-origin",
  "position",
  "agent-id",
  "theme",
  "locale",
  "open",
  "inline",
  "skip-resolve",
] as const;

/**
 * Framework-agnostic custom element.
 *
 * ```html
 * <script type="module">
 *   import '@monti/embed-web-component';
 * </script>
 * <monti-embed
 *   embed-key="emb_…"
 *   api-base="http://localhost:8091"
 *   position="bottom-right"
 * ></monti-embed>
 * ```
 */
export class MontiEmbedElement extends HTMLElement {
  static get observedAttributes(): string[] {
    return [...OBSERVED];
  }

  private embed: MontiEmbed | null = null;
  private mountToken = 0;
  private host: HTMLDivElement | null = null;

  connectedCallback(): void {
    if (!this.host) {
      this.host = document.createElement("div");
      this.host.style.display = this.hasAttribute("inline") ? "block" : "contents";
      if (this.hasAttribute("inline")) {
        this.host.style.width = "100%";
        this.host.style.minHeight = "480px";
        this.host.style.height = "100%";
      }
      this.appendChild(this.host);
    }
    void this.remount();
  }

  disconnectedCallback(): void {
    this.teardown();
  }

  attributeChangedCallback(): void {
    if (!this.isConnected) return;
    void this.remount();
  }

  /** Imperative API for Angular / plain JS hosts. */
  open(): void {
    this.embed?.open();
  }

  close(): void {
    this.embed?.close();
  }

  toggle(): void {
    this.embed?.toggle();
  }

  getInstance(): MontiEmbed | null {
    return this.embed;
  }

  private teardown(): void {
    this.mountToken += 1;
    this.embed?.destroy();
    this.embed = null;
  }

  private attr(name: string): string {
    return (this.getAttribute(name) || "").trim();
  }

  private boolAttr(name: string): boolean {
    if (!this.hasAttribute(name)) return false;
    const v = (this.getAttribute(name) || "").toLowerCase();
    return v === "" || v === "true" || v === "1" || v === "yes";
  }

  private async remount(): Promise<void> {
    const token = ++this.mountToken;
    this.embed?.destroy();
    this.embed = null;

    const embedKey = this.attr("embed-key");
    const apiBase = this.attr("api-base");
    if (!embedKey || !apiBase) {
      this.dispatchEvent(
        new CustomEvent("monti-error", {
          detail: {
            code: !embedKey ? "missing_embed_key" : "missing_api_base",
            message: !embedKey ? "embed-key is required" : "api-base is required",
          } satisfies EmbedError,
          bubbles: true,
        }),
      );
      return;
    }

    const inline = this.boolAttr("inline");
    if (this.host) {
      this.host.style.display = inline ? "block" : "contents";
    }

    const position = (this.attr("position") || "bottom-right") as EmbedPosition;
    const embed = new MontiEmbed({
      embedKey,
      apiBase,
      parentOrigin: this.attr("parent-origin") || undefined,
      position,
      agentId: this.attr("agent-id") || undefined,
      theme: this.attr("theme") || undefined,
      locale: this.attr("locale") || undefined,
      open: this.boolAttr("open"),
      skipResolve: this.boolAttr("skip-resolve"),
      container: inline ? this.host : null,
      onOpen: () => this.dispatchEvent(new CustomEvent("monti-open", { bubbles: true })),
      onClose: () => this.dispatchEvent(new CustomEvent("monti-close", { bubbles: true })),
      onReady: (result?: EmbedResolveResult) =>
        this.dispatchEvent(new CustomEvent("monti-ready", { detail: result, bubbles: true })),
      onError: (error: EmbedError) =>
        this.dispatchEvent(new CustomEvent("monti-error", { detail: error, bubbles: true })),
      onDestroy: () => this.dispatchEvent(new CustomEvent("monti-destroy", { bubbles: true })),
    });

    await embed.mount();
    if (token !== this.mountToken) {
      embed.destroy();
      return;
    }
    this.embed = embed;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "monti-embed": MontiEmbedElement;
  }
}

export function defineMontiEmbedElement(tagName = "monti-embed"): void {
  if (typeof customElements === "undefined") return;
  if (customElements.get(tagName)) return;
  customElements.define(tagName, MontiEmbedElement);
}

// Auto-register when imported in the browser
defineMontiEmbedElement();

export default MontiEmbedElement;
